apiVersion: batch/v1beta1
kind: CronJob
metadata:
  name: example-cronjob
spec:
  schedule: "0 19 * * *"  # Spustí se každý den v 19:00
  jobTemplate:
    spec:
      template:
        spec:
          containers:
          - name: example
            image: busybox
            command: ["echo", "Hello, Kubernetes!"]
          restartPolicy: OnFailure
      backoffLimit: 3  # Maximálně 3 opakování v případě neúspěchu
