apiVersion: apps/v1
kind: Deployment
metadata:
  name: my-app
  labels:
    app: my-app
spec:
  replicas: 2
  selector:
    matchLabels:
      app: my-app
  template:
    metadata:
      labels:
        app: my-app
    spec:
      containers:
      - name: my-app-container
        image: 891377251179.dkr.ecr.eu-central-1.amazonaws.com/my-public-repo:latest
        ports:
        - containerPort: 80
      imagePullSecrets:
      - name: regcred
