name: Build and Push Docker Image

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Log in to Amazon ECR
        env:
          AWS_REGION: eu-central-1
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        run: |
          aws ecr get-login-password --region $AWS_REGION | docker login --username AWS --password-stdin 891377251179.dkr.ecr.eu-central-1.amazonaws.com

      - name: Build and push Docker image
        uses: docker/build-push-action@v2
        with:
          context: ./postman
          push: true
          tags: 891377251179.dkr.ecr.eu-central-1.amazonaws.com/my-public-repo:latest

      - name: Image digest
        run: echo ${{ steps.build-image.outputs.digest }}
