name: Build and Push Docker Image

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Log in to Amazon ECR
        id: login-ecr
        uses: aws-actions/amazon-ecr-login@v1
        with:
          region: eu-central-1 # Change this to your AWS region
          profile: main

      - name: Build and push Docker image
        id: build-image
        uses: docker/build-push-action@v2
        with:
          context: ./postman
          push: true
          tags: 891377251179.dkr.ecr.eu-central-1.amazonaws.com/my-public-repo:latest

      - name: Image digest
        run: echo ${{ steps.build-image.outputs.digest }}
